# Generated by Django 3.2.12 on 2022-05-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_casino_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='casino_points',
            field=models.IntegerField(default=100000, null=True),
        ),
    ]
