# Generated by Django 3.2.12 on 2022-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('backdrop_path', models.CharField(max_length=200)),
                ('genre_ids', models.ManyToManyField(related_name='movie_genre', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('profile_path', models.CharField(blank=True, max_length=200, null=True)),
                ('popularity', models.FloatField()),
                ('birthday', models.DateField(null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_ids', models.ManyToManyField(related_name='person_movie', to='movies.Movie')),
            ],
        ),
    ]
